# Generated by Django 4.1 on 2022-08-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number_cluster', models.CharField(max_length=10)),
                ('date_timestamp', models.CharField(max_length=40)),
                ('product_name', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
                ('code_level', models.CharField(max_length=40)),
                ('number_of_enclosure', models.IntegerField()),
            ],
        ),
    ]
