# Generated by Django 4.1 on 2022-08-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnclosureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number_cluster', models.CharField(max_length=10)),
                ('date_timestamp', models.CharField(max_length=40)),
                ('id_enclosure', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
                ('temperature', models.CharField(max_length=40)),
                ('total_PSUs', models.CharField(max_length=40)),
                ('product_MTM_enclosure', models.CharField(max_length=40)),
                ('serial_number_enclosure', models.CharField(max_length=40)),
                ('status_enclosure', models.CharField(max_length=40)),
                ('online_PSUs', models.CharField(max_length=40)),
                ('drive_slots', models.CharField(max_length=40)),
                ('fault_LED', models.CharField(max_length=40)),
                ('identify_LED', models.CharField(max_length=40)),
                ('total_canisters', models.CharField(max_length=40)),
                ('online_canisters', models.CharField(max_length=40)),
            ],
        ),
    ]
