# Generated by Django 4.1 on 2022-08-28 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0002_enclosuremodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='enclosuremodel',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snap_analyzer_django.generalcluster'),
        ),
    ]
