# Generated by Django 4.1 on 2022-09-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0003_enclosuremodel_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enclosuremodel',
            name='cluster',
        ),
        migrations.AddField(
            model_name='enclosuremodel',
            name='name_node_id_1',
            field=models.CharField(default='Null', max_length=40),
            preserve_default=False,
        ),
    ]
