# Generated by Django 4.1 on 2022-09-01 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0004_remove_enclosuremodel_cluster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enclosuremodel',
            name='name_node_id_1',
        ),
    ]
