# Generated by Django 4.1 on 2022-09-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0006_enclosuremodel_name_node_id_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enclosuremodel',
            old_name='name_node_id_1',
            new_name='nameNode1',
        ),
    ]
