# Generated by Django 4.1 on 2022-09-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0007_rename_name_node_id_1_enclosuremodel_namenode1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enclosuremodel',
            old_name='nameNode1',
            new_name='name_node_id_1',
        ),
    ]
