# Generated by Django 4.1 on 2022-09-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0008_rename_namenode1_enclosuremodel_name_node_id_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='enclosuremodel',
            name='status_node_id_1',
            field=models.CharField(default='Null', max_length=40),
            preserve_default=False,
        ),
    ]
