# Generated by Django 4.1 on 2022-09-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0009_enclosuremodel_status_node_id_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='enclosuremodel',
            name='service_IP_address_node_id_1',
            field=models.CharField(default='Null', max_length=40),
            preserve_default=False,
        ),
    ]
