# Generated by Django 4.1 on 2022-09-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0010_enclosuremodel_service_ip_address_node_id_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='enclosuremodel',
            name='node_id_1_WWNN',
            field=models.CharField(default='Null', max_length=40),
            preserve_default=False,
        ),
    ]
