# Generated by Django 4.1 on 2022-09-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0013_rename_node_id_1_wwnn_enclosuremodel_node_left_wwnn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enclosuremodel',
            old_name='node_left_WWNN',
            new_name='IO_group_id_node_left',
        ),
    ]
