# Generated by Django 4.1 on 2022-09-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0014_rename_node_left_wwnn_enclosuremodel_io_group_id_node_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='enclosuremodel',
            name='IO_group_id_node_right',
            field=models.CharField(default='Null', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enclosuremodel',
            name='id_node_right',
            field=models.CharField(default=12, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enclosuremodel',
            name='name_node_right',
            field=models.CharField(default='Null', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enclosuremodel',
            name='service_IP_address_node_right',
            field=models.CharField(default='Null', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enclosuremodel',
            name='status_node_right',
            field=models.CharField(default='Null', max_length=40),
            preserve_default=False,
        ),
    ]
