# Generated by Django 4.1 on 2022-09-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0015_enclosuremodel_io_group_id_node_right_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enclosuremodel',
            name='online_batteries',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
