# Generated by Django 4.1 on 2022-09-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0017_remove_enclosuremodel_total_psus'),
    ]

    operations = [
        migrations.AddField(
            model_name='enclosuremodel',
            name='total_PSUs',
            field=models.CharField(default='2', max_length=40),
            preserve_default=False,
        ),
    ]
