# Generated by Django 4.1 on 2022-09-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0018_enclosuremodel_total_psus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number_enclosure', models.CharField(max_length=10)),
                ('date_timestamp', models.CharField(max_length=40)),
                ('drive_id', models.CharField(max_length=40)),
                ('drive_status', models.CharField(max_length=40)),
                ('drive_use', models.CharField(max_length=40)),
                ('capacity', models.CharField(max_length=40)),
                ('drive_slot_id', models.CharField(max_length=40)),
                ('id_enclosure', models.CharField(max_length=40)),
            ],
        ),
    ]
