# Generated by Django 4.1 on 2022-09-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0019_drivemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivemodel',
            name='serial_number_cluster',
            field=models.CharField(default='Null', max_length=10),
            preserve_default=False,
        ),
    ]
