# Generated by Django 4.1 on 2022-09-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0020_drivemodel_serial_number_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivemodel',
            name='drive_slot_id',
            field=models.IntegerField(),
        ),
    ]
