# Generated by Django 4.1 on 2022-09-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0021_alter_drivemodel_drive_slot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivemodel',
            name='vendor_id',
            field=models.CharField(default='Null', max_length=40),
            preserve_default=False,
        ),
    ]
