# Generated by Django 4.1 on 2022-09-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0023_remove_drivemodel_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivemodel',
            name='vendor_id',
            field=models.CharField(default='Nulllllllll', max_length=40),
            preserve_default=False,
        ),
    ]
