# Generated by Django 4.1 on 2022-09-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0024_drivemodel_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivemodel',
            name='FRU_identity',
            field=models.CharField(default='Nuul', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivemodel',
            name='FRU_part_number',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivemodel',
            name='firmware_level',
            field=models.CharField(default='Null', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivemodel',
            name='mdisk_id',
            field=models.CharField(default='Null', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivemodel',
            name='mdisk_name',
            field=models.CharField(default='Null', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivemodel',
            name='product_id',
            field=models.CharField(default='Null', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivemodel',
            name='transport_protocol',
            field=models.CharField(default='Null', max_length=40),
            preserve_default=False,
        ),
    ]
