# Generated by Django 4.1 on 2022-09-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0025_drivemodel_fru_identity_drivemodel_fru_part_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number_cluster', models.CharField(max_length=10)),
                ('date_timestamp', models.CharField(max_length=40)),
                ('serial_number_enclosure', models.CharField(max_length=40)),
                ('id_node', models.CharField(max_length=40)),
                ('name_node', models.CharField(max_length=40)),
                ('status_node', models.CharField(max_length=40)),
                ('service_IP_address', models.CharField(max_length=40)),
                ('IO_group_id_node', models.CharField(max_length=40)),
            ],
        ),
    ]
