# Generated by Django 4.1 on 2022-09-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0026_nodemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enclosuremodel',
            name='IO_group_id_node_left',
        ),
        migrations.RemoveField(
            model_name='enclosuremodel',
            name='IO_group_id_node_right',
        ),
        migrations.RemoveField(
            model_name='enclosuremodel',
            name='name_node_left',
        ),
        migrations.RemoveField(
            model_name='enclosuremodel',
            name='name_node_right',
        ),
        migrations.RemoveField(
            model_name='enclosuremodel',
            name='service_IP_address_node_left',
        ),
        migrations.RemoveField(
            model_name='enclosuremodel',
            name='service_IP_address_node_right',
        ),
        migrations.RemoveField(
            model_name='enclosuremodel',
            name='status_node_left',
        ),
        migrations.RemoveField(
            model_name='enclosuremodel',
            name='status_node_right',
        ),
    ]
