# Generated by Django 4.1 on 2022-09-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0027_remove_enclosuremodel_io_group_id_node_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodemodel',
            name='WWNN_node',
            field=models.CharField(default='1111111111111', max_length=40),
            preserve_default=False,
        ),
    ]
