# Generated by Django 4.1 on 2022-09-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0028_nodemodel_wwnn_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodemodel',
            name='IO_group_name',
            field=models.CharField(default='AXE', max_length=40),
            preserve_default=False,
        ),
    ]
