# Generated by Django 4.1 on 2022-09-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0029_nodemodel_io_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodemodel',
            name='partner_node_id',
            field=models.CharField(default='99', max_length=40),
            preserve_default=False,
        ),
    ]
