# Generated by Django 4.1 on 2022-09-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0030_nodemodel_partner_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodemodel',
            name='partner_node_name',
            field=models.CharField(default='nodddddddd', max_length=40),
            preserve_default=False,
        ),
    ]
