# Generated by Django 4.1 on 2022-09-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0031_nodemodel_partner_node_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodemodel',
            name='config_node',
            field=models.CharField(default='Да', max_length=40),
            preserve_default=False,
        ),
    ]
