# Generated by Django 4.1 on 2022-09-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0032_nodemodel_config_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodemodel',
            name='iscsi_name',
            field=models.CharField(default='iqs', max_length=40),
            preserve_default=False,
        ),
    ]
