# Generated by Django 4.1 on 2022-09-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_analyzer_django', '0036_nodemodel_product_mtm'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodemodel',
            name='code_level',
            field=models.CharField(default='7.7777777777', max_length=40),
            preserve_default=False,
        ),
    ]
